"use client";
import {useState} from "react";
const empty={name:"",price:"",tag:"",conc:"EDP · 20%",longevity:3,sillage:3,top:"",heart:"",base:"",desc:"",stock:0,image_url:""};
const money=n=>`Rs. ${Number(n||0).toLocaleString("en-PK")}`;
export default function Admin(){
 const [key,setKey]=useState(""),[logged,setLogged]=useState(false),[products,setProducts]=useState([]),[orders,setOrders]=useState([]),[form,setForm]=useState(empty),[editing,setEditing]=useState(null),[tab,setTab]=useState("products");
 async function load(){const h={"x-admin-key":key};const p=await fetch("/api/admin/products",{headers:h});const o=await fetch("/api/admin/orders",{headers:h});if(p.ok&&o.ok){setProducts((await p.json()).products||[]);setOrders((await o.json()).orders||[]);setLogged(true)}else alert("Invalid admin password/key");}
 const set=(k,v)=>setForm(f=>({...f,[k]:v}));
 async function save(e){e.preventDefault();const r=await fetch("/api/admin/products",{method:editing?"PUT":"POST",headers:{"Content-Type":"application/json","x-admin-key":key},body:JSON.stringify(editing?{...form,id:editing}:form)});if(r.ok){setForm(empty);setEditing(null);load()}else alert((await r.json()).error||"Save failed")}
 async function del(id){if(!confirm("Delete this perfume?"))return;await fetch("/api/admin/products",{method:"DELETE",headers:{"Content-Type":"application/json","x-admin-key":key},body:JSON.stringify({id})});load()}
 if(!logged)return <main className="admin"><div className="panel" style={{maxWidth:480,margin:"60px auto"}}><div className="eyebrow">PRIVATE AREA</div><h1>Champion Admin</h1><input type="password" placeholder="Admin password" value={key} onChange={e=>setKey(e.target.value)}/><button className="btn dark" onClick={load}>Sign in</button></div></main>;
 const revenue=orders.reduce((s,o)=>s+Number(o.total||0),0);
 return <main className="admin"><div className="head"><div><div className="eyebrow">CONTROL CENTER</div><h1>Champion Admin</h1></div><button className="btn outline" onClick={()=>setLogged(false)}>Sign out</button></div>
 <div className="benefits"><div><b>PRODUCTS</b><p>{products.length}</p></div><div><b>ORDERS</b><p>{orders.length}</p></div><div><b>REVENUE</b><p>{money(revenue)}</p></div><div><b>PENDING</b><p>{orders.filter(o=>o.status==="pending").length}</p></div></div>
 <div className="buttons" style={{margin:"25px 0"}}><button className="btn dark" onClick={()=>setTab("products")}>Products</button><button className="btn gold" onClick={()=>setTab("orders")}>Orders</button></div>
 {tab==="products"&&<div className="admin-grid"><div className="panel"><h2>{editing?"Edit perfume":"Add new perfume"}</h2><form onSubmit={save}>{["name","price","tag","conc","top","heart","base","stock","image_url"].map(k=><input key={k} required={k==="name"||k==="price"} type={k==="price"||k==="stock"?"number":"text"} placeholder={k.replace("_"," ")} value={form[k]} onChange={e=>set(k,e.target.value)}/>)}<textarea placeholder="Description" value={form.desc} onChange={e=>set("desc",e.target.value)}/><label>Longevity {form.longevity}/5<input type="range" min="1" max="5" value={form.longevity} onChange={e=>set("longevity",e.target.value)}/></label><label>Sillage {form.sillage}/5<input type="range" min="1" max="5" value={form.sillage} onChange={e=>set("sillage",e.target.value)}/></label><button className="btn dark">{editing?"Update perfume":"Add perfume"}</button>{editing&&<button type="button" className="btn outline" onClick={()=>{setEditing(null);setForm(empty)}}>Cancel</button>}</form></div>
 <div className="panel"><h2>Your perfumes</h2>{products.map(p=><div className="order" key={p.id}><b>{p.name}</b> · {money(p.price)} · Stock {p.stock}<br/><button onClick={()=>{setEditing(p.id);setForm(p)}}>Edit</button> <button onClick={()=>del(p.id)}>Delete</button></div>)}</div></div>}
 {tab==="orders"&&<div className="panel"><h2>Customer orders</h2>{orders.map(o=><div className="order" key={o.id}><b>Order #{o.id}</b> · {money(o.total)} · {o.status}<br/>{o.customer_name} · {o.email} · {o.phone}<br/>{o.address}, {o.city} {o.postal_code}</div>)}</div>}
 </main>
}
