"use client";
import {useEffect,useState} from "react";
const seedProducts=[
{id:1,name:"Podium",price:78,tag:"The one you wear when you already know you've won.",conc:"EDP · 20%",longevity:4,sillage:4,top:"Bergamot, Black Pepper, Pink Grapefruit",heart:"Leather, Violet, Cedar",base:"Amber, Vetiver, Musk",desc:"A sharp, confident opener that softens into warm leather and amber."},
{id:2,name:"Finish Line",price:68,tag:"Clean speed. Nothing wasted.",conc:"EDT · 15%",longevity:3,sillage:3,top:"Mint, Yuzu, Ginger",heart:"Sea Salt, White Tea, Neroli",base:"White Musk, Driftwood",desc:"Fresh and fast-moving, like the last stretch before the tape."},
{id:3,name:"Gold Standard",price:92,tag:"The benchmark everyone else gets compared to.",conc:"Parfum · 28%",longevity:5,sillage:5,top:"Saffron, Cardamom, Blood Orange",heart:"Oud, Rose, Tobacco Leaf",base:"Sandalwood, Amber, Vanilla",desc:"Rich and unmistakable. Our flagship scent — deep, warm, and built to be remembered."}
];
function Bottle(){return <div className="p-bottle"><div className="p-cap"/><strong>CHAMPION</strong><small>PERFUMES</small></div>}
export default function Store(){
 const [cart,setCart]=useState([]),[products,setProducts]=useState(seedProducts),[selected,setSelected]=useState(null),[openCart,setOpenCart]=useState(false),[message,setMessage]=useState("");
 useEffect(()=>{setCart(JSON.parse(localStorage.getItem("champion-cart")||"[]"));fetch("/api/products",{cache:"no-store"}).then(r=>r.json()).then(x=>x.products?.length&&setProducts(x.products)).catch(()=>{})},[]);
 useEffect(()=>{localStorage.setItem("champion-cart",JSON.stringify(cart))},[cart]);
 const add=p=>setCart(c=>{let x=c.find(i=>i.id===p.id);return x?c.map(i=>i.id===p.id?{...i,qty:i.qty+1}:i):[...c,{...p,qty:1}]});
 const total=cart.reduce((s,p)=>s+p.price*p.qty,0);
 const submitSupport=e=>{e.preventDefault();setMessage("Message received — thank you.");e.target.reset()};
 return <><div className="announcement">✦ FREE SHIPPING ON ALL ORDERS OVER $75 ✦</div>
 <header className="header"><a className="logo" href="#">CHAMPION<small>PERFUMES</small></a><nav className="nav"><a href="#home">Home</a><a href="#shop">Shop</a><a href="#about">About</a><a href="#support">Support</a></nav><div className="actions"><button onClick={()=>setOpenCart(true)}>🛒 {cart.reduce((s,p)=>s+p.qty,0)}</button></div></header>
 <main><section id="home" className="hero"><div className="hero-copy"><div className="eyebrow">A NEW FRAGRANCE HOUSE</div><h1>Fragrance built for the moment you <em>win.</em></h1><p>Champion is a perfume house for people who show up ready. Every scent is measured, tested, and rated like a performance — not just described.</p><div className="buttons"><a className="btn gold" href="#shop">Shop the collection</a><a className="btn outline" href="#about">Our story</a></div></div><div className="bottle-wrap"><div className="bottle"><div className="cap"/><div className="glass"><strong>CHAMPION</strong><small>PERFUMES</small></div></div></div></section>
 <section id="shop" className="section"><div className="head"><div><div className="eyebrow">THE COLLECTION</div><h2>Our Fragrances</h2></div></div><div className="products">{products.map(p=><article className="product" key={p.id} onClick={()=>setSelected(p)}><div className="visual"><Bottle/></div><div className="info"><div className="top"><h3>{p.name}</h3><span className="price">${p.price}</span></div><div className="tag">{p.tag}</div><div className="meta">{p.conc} · LONGEVITY {p.longevity}/5 · SILLAGE {p.sillage}/5</div></div></article>)}</div></section>
 <section className="benefits"><div><b>✦ PREMIUM INGREDIENTS</b><p>Sourced from the world's finest fragrance houses.</p></div><div><b>✦ PERFORMANCE TESTED</b><p>Every scent is tested for longevity and sillage.</p></div><div><b>✦ FREE SHIPPING</b><p>Free shipping over $75.</p></div><div><b>✦ 30-DAY RETURNS</b><p>Simple and hassle-free.</p></div></section>
 <section id="about" className="story"><div><div className="eyebrow">OUR STORY</div><h2>More than a scent.<br/>It's a standard.</h2><p>Champion started with a simple idea: fragrance should feel like getting ready for something that matters — a win, a first day, a night you'll remember.</p><p>We treat every scent like a performance, not just a story.</p></div><div className="bottle-wrap"><div className="bottle"><div className="cap"/><div className="glass"><strong>CHAMPION</strong><small>PERFUMES</small></div></div></div></section>
 <section id="support" className="section support"><div className="eyebrow">SUPPORT</div><h2>How can we help?</h2><div className="support-grid"><div><h3>Questions about a scent?</h3><p>Tell us what you're looking for and we'll help you choose.</p></div><form onSubmit={submitSupport}><input required placeholder="Your name"/><input required type="email" placeholder="Email address"/><textarea required placeholder="Your message"/><button className="btn dark">Send message</button><span className="status">{message}</span></form></div></section></main>
 <footer className="footer"><span>© {new Date().getFullYear()} Champion Perfumes</span><span>Built for the moment you win.</span></footer>
 {selected&&<div className="modal" onClick={()=>setSelected(null)}><div className="card" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}>×</button><div className="modalvisual"><Bottle/></div><div className="modalbody"><div className="modaltop"><div><h2>{selected.name}</h2><p>{selected.tag}</p></div><strong>${selected.price}</strong></div><p>{selected.desc}</p><p><b>{selected.conc}</b> · Longevity {selected.longevity}/5 · Sillage {selected.sillage}/5</p><div className="notes"><div><b>Top</b><br/>{selected.top}</div><div><b>Heart</b><br/>{selected.heart}</div><div><b>Base</b><br/>{selected.base}</div></div><button className="btn dark full" onClick={()=>{add(selected);setSelected(null);setOpenCart(true)}}>Add to cart</button></div></div></div>}
 {openCart&&<><div className="cart"><div className="carthead"><h2>Your Cart</h2><button className="close" onClick={()=>setOpenCart(false)}>×</button></div>{cart.length?cart.map(p=><div className="cartitem" key={p.id}><div><b>{p.name}</b><br/><small>${p.price} × {p.qty}</small></div><button onClick={()=>setCart(c=>c.filter(x=>x.id!==p.id))}>Remove</button></div>):<p>Your cart is empty.</p>}<div className="cartbottom"><div>Total <b>${total.toFixed(2)}</b></div><a className="btn gold full" href="/checkout">Proceed to checkout</a></div></div></>}
 </> }
